- import_role:
    name: consul-install
- import_role:
    name: consul-encryption-key-check
- name: Copy consul configuration to servers
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/consul.d/{{ item }}"
    mode: "640"
    owner: consul
    group: consul
  loop:
    - client.hcl
  vars:
    retry_join_servers: "{{ groups.subject_consul_server }}"
- name: Copy Resolved configuration to servers
  become: true
  ansible.builtin.template:
    src: "resolved.conf.j2"
    dest: "/etc/systemd/resolved.conf"
    mode: "644"
    owner: root
    group: root
- name: Validate consul configuration
  become: true
  command: "consul validate /etc/consul.d/{{ item }}"
  loop:
    - client.hcl
- name: Enable consul service
  become: true
  ansible.builtin.systemd:
    name: consul-client
    enabled: true
- name: Start consul service
  become: true
  ansible.builtin.systemd:
    name: consul-client
    state: started
- name: Restart consul service
  become: true
  ansible.builtin.systemd:
    name: consul-client
    state: restarted
- name: Reload Daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
- name: Copy over systemd service file
  become: true
  ansible.builtin.template:
    src: consul-client.service.j2
    dest: /usr/lib/systemd/system/consul-client.service
    mode: "660"
    owner: consul
    group: consul
- name: Forward TCP traffic to consul
  become: true
  ansible.builtin.iptables:
    table: nat
    destination: localhost
    protocol: tcp
    match: tcp
    destination_port: 8600
    source_port: 53
- name: Forward UDP traffic to consul
  become: true
  ansible.builtin.iptables:
    table: nat
    destination: localhost
    protocol: udp
    match: udp
    destination_port: 8600
    source_port: 53