---
- name: Setup Consul
  hosts: subject_consul
  vars:
    consul_version: "1.9.5"
  tasks:
    - name: Ensure consul group exists
      ansible.builtin.group:
        name: consul
        state: present
      become: true
    - name: Ensure consul user exists
      ansible.builtin.user:
        name: consul
        group: consul
        system: true
        home: /etc/consul.d
        shell: /bin/false
        createhome: true
      become: true
    - name: Ensure dependencies are installed
      package:
        name: unzip
        state: present
      become: true
    - name: Download binary zip
      ansible.builtin.get_url: 
        url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: "/tmp/"
        checksum: "sha256:https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_SHA256SUMS"
        owner: consul
        group: consul
      become: true
    - name: Ensure directory exists
      ansible.builtin.file:
        path: /opt/consul
        state: directory
        owner: consul
        group: consul
      become: true
    - name: Unzip binary
      ansible.builtin.unarchive:
        src: "/tmp/consul_{{ consul_version }}_linux_amd64.zip"
        dest: /usr/bin/
        remote_src: true
        owner: consul
        group: consul
      become: true
    - name: Verify that consul is usable
      command: "consul --version"
    - set_fact: 
        bootstrap_hostname: "{{ ansible_play_hosts | random }}"
    - name: Generate keygen
      command: consul keygen
      register: consul_key
      when: inventory_hostname == bootstrap_hostname
    # https://learn.hashicorp.com/tutorials/consul/deployment-guide#generate-tls-certificates-for-rpc-encryption
    # - name: Generate tls certificates for rpc encryption
    #   command: consul tls ca create
    - name: Copy bootstrap configuration to bootstrap server
      ansible.builtin.template:
        src: bootstrap.hcl.j2
        dest: /etc/consul.d/bootstrap.hcl
        mode: "640"
        owner: consul
        group: consul
      when: inventory_hostname == bootstrap_hostname
      become: true
    - name: Copy non-bootstrap configuration to non-bootstrap servers
      ansible.builtin.template:
        src: server.hcl.j2
        dest: /etc/consul.d/sever.hcl
        mode: "640"
        owner: consul
        group: consul
      when: inventory_hostname != bootstrap_hostname
      become: true
    # https://learn.hashicorp.com/tutorials/consul/deployment-guide#configure-systemd
    # - name: Copy over systemd service file
    # # https://learn.hashicorp.com/tutorials/consul/deployment-guide#start-the-consul-service
    # - name: Validate consul configuration
    # - name: Enable consul service
    # - name: Start consul service


# - name: Setup Consul
#   hosts: subject_consul
#   tasks:
#     # TODO: Keys are output in plain text, how can we auto add them to the config file in e
#     - name: Generate keygen
#       command: consul keygen
#       register: consul_key
#     # - name: Run agent
