---
- name: Setup Nomad Client
  hosts: subject_nomad_client
  vars:
    consul_version: "1.9.5"
    vault_version: "1.7.2"
    nomad_version: "1.1.0"
  tasks:
    - amazon.aws.ec2_metadata_facts:
    - import_role:
        name: general-setup
    - import_role:
        name: consul-client-setup
    - import_role:
        name: vault-install
    - import_role:
        name: nomad-install
    - name: Copy over systemd service file
      become: true
      ansible.builtin.template:
        src: nomad-client.service.j2
        dest: /etc/systemd/system/nomad-client.service
        mode: "660"
        owner: nomad
        group: nomad
    - name: Copy over nomad configuration files
      become: true
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/etc/nomad.d/{{ item }}"
        mode: "700"
        owner: nomad
        group: nomad
      loop:
        - "nomad-client.hcl"
    - name: Enable nomad service
      become: true
      ansible.builtin.systemd:
        name: nomad-client
        enabled: true
    - name: Start nomad service
      become: true
      ansible.builtin.systemd:
        name: nomad-client
        state: started
    - name: Restart nomad service
      become: true
      ansible.builtin.systemd:
        name: nomad-client
        state: restarted
    - name: Reload Daemon
      become: true
      ansible.builtin.systemd:
        daemon_reload: true