    - name: Copy consul configuration to servers
      become: true
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/etc/consul.d/{{ item }}"
        mode: "640"
        owner: consul
        group: consul
      loop:
        - client.hcl
    - name: Copy over systemd service file
      become: true
      ansible.builtin.template:
        src: consul.service.j2
        dest: /usr/lib/systemd/system/consul-agent.service
        mode: "660"
        owner: consul
        group: consul
    - name: Validate consul configuration
      become: true
      command: "consul validate /etc/consul.d/{{ item }}"
      loop:
        - client.hcl
    - name: Enable consul service
      become: true
      ansible.builtin.systemd:
        name: consul-client
        enabled: true
    - name: Start consul service
      become: true
      ansible.builtin.systemd:
        name: consul-client
        state: started
    - name: Restart consul service
      become: true
      ansible.builtin.systemd:
        name: consul-client
        state: restarted
    - name: Reload Daemon
      become: true
      ansible.builtin.systemd:
        daemon_reload: true