- hosts: localhost
  tasks:
    - name: Remove tmp directories
      ansible.builtin.file:
        path: playbooks/*/tmp/
        state: absent
    # - name: Terraform destroy
    #   shell: terraform destroy -auto-approve